import mongoose from "mongoose";

export const ApiRecord = new mongoose.Schema({
    id: {type: String, required: true},
    title: {type: String, required: true},
    summary: {type: String, required: true},
    rating: {type: Number, required: true},
    name: {type: String, required: true},
    label: {type: String, required: true},
    author: {type: String, required: true},
    description: {type: String, required: true},
    type: {},
    downloads : {type: Number, required: true},
    useCount : {type: Number, required: true},
    sampleUrl: {type: String, required: true},
    downloadUrl : {type: String, required: true},
    dateModified: {type: Date, required: true},
    remoteFeed : {type: String, required: true},
    numComments : {type: Number, required: true},
    commentsUrl: {type: String, required: true},
    Tags: {},
    category: {type: String, required: true},
    protocols: {},
    serviceEndpoint: {type: String, required: true},
    version : {type: Number, required: true},
    wsdl : {type: String, required: true},
    data_formats: {},
    api_groups : {},
    example : {type: String, required: true},
    clientInstall : {type: String, required: true},
    authentication : {type: String, required: true},
    ssl : {type: String, required: true},
    readonly : {type: String, required: true},
    VendorApiKits : {},
    CommunityApiKits : {},
    blog : {type: String, required: true},
    forum : {type: String, required: true},
    support : {type: String, required: true},
    accountReq: {},
    commercial : {type: String, required: true},
    provider: {type: String, required: true},
    managedBy : {type: String, required: true},
    nonCommercial : {type: String, required: true},
    dataLicensing : {type: String, required: true},
    fees : {type: String, required: true},
    limits : {type: String, required: true},
    terms : {type: String, required: true},
    company : {type: String, required: true},
    updated: {type: Date, required: true}
});